export const COLUMN_DEFINITIONS = [
  { key: "participant_id", label: "ID", visible: true, show: true, filterable: false, sortable: true, sorting: true },
  { key: "first_name", label: "Nombre", visible: true, show: true, filterable: false, sortable: true, sorting: false },
  { key: "last_name", label: "Apellidos", visible: true, show: true, filterable: false, sortable: true, sorting: false },
  { key: "preferred_name", label: "Nombre preferido", visible: true, show: false, filterable: false, sortable: true, sorting: false },
  { key: "dob", label: "Nacimiento", visible: true, show: false, filterable: false, sortable: false, sorting: false },
  { key: "sex", label: "Género", visible: true, show: true, filterable: true, sortable: false, sorting: false },
  { key: "mobile_number", label: "Número", visible: true, show: true, filterable: false, sortable: false, sorting: false },
  { key: "email", label: "Correo", visible: true, show: true, filterable: false, sortable: false, sorting: false },
  { key: "age", label: "Edad", visible: true, show: true, filterable: false, sortable: true, sorting: false },
  { key: "shirt_size", label: "Talla", visible: true, show: false, filterable: false, sortable: true, sorting: false },
  { key: "member_of_church", label: "Miembro de la Iglesia", visible: true, show: false, filterable: true, sortable: false, sorting: false },
  { key: "stake", label: "Estaca", visible: true, show: true, filterable: false, sortable: true, sorting: false },
  { key: "ward", label: "Barrio", visible: true, show: true, filterable: false, sortable: true, sorting: false },
  { key: "blood_type", label: "Tipo de sangre", visible: false, show: false, filterable: false, sortable: false, sorting: false },
  { key: "allergies", label: "Alergias", visible: false, show: false, filterable: false, sortable: false, sorting: false },
  { key: "treatment", label: "Tratamiento", visible: false, show: false, filterable: false, sortable: false, sorting: false },
  { key: "diabetic_or_asthathic", label: "Diabetes o Asma", visible: false, show: false, filterable: false, sortable: false, sorting: false },
  { key: "health_insurance", label: "Seguro de Salud", visible: false, show: false, filterable: false, sortable: false, sorting: false },
  { key: "covid_vaccine_doses", label: "Dosis Covid", visible: false, show: false, filterable: false, sortable: false, sorting: false },
  { key: "payment", label: "Pagado", visible: true, show: false, filterable: true, sortable: false, sorting: false },
  { key: "early_retirement", label: "Retiro temprano", visible: false, show: false, filterable: false, sortable: false, sorting: false },
  { key: "attendace", label: "Asistió", visible: false, show: false, filterable: false, sortable: false, sorting: false },
  { key: "is_counselor", label: "Es Consejero(a)", visible: false, show: false, filterable: false, sortable: false, sorting: false },
  { key: "company_id", label: "Compañía", visible: true, show: false, filterable: false, sortable: true, sorting: false },
];
